// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-O8uKsdeoLz0hemAy5IFnXImOmYCcZaU',
    appId: '1:897007121549:web:f5ef01ec586515f5319ec4',
    messagingSenderId: '897007121549',
    projectId: 'foodbridge-e84e0',
    authDomain: 'foodbridge-e84e0.firebaseapp.com',
    storageBucket: 'foodbridge-e84e0.firebasestorage.app',
    measurementId: 'G-1KLNGPKR9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYup57qQQk1cgoYe980gHT8hgBCVhLKM',
    appId: '1:897007121549:android:f7c5aec970f2753a319ec4',
    messagingSenderId: '897007121549',
    projectId: 'foodbridge-e84e0',
    storageBucket: 'foodbridge-e84e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2tvYjOAfxqaHJVYo6eOIzaSoqrlxcVM',
    appId: '1:897007121549:ios:25bdc769b87a0e2a319ec4',
    messagingSenderId: '897007121549',
    projectId: 'foodbridge-e84e0',
    storageBucket: 'foodbridge-e84e0.firebasestorage.app',
    androidClientId: '897007121549-4mm4sr2dad8g636ha1bf3r62b4m4ipfe.apps.googleusercontent.com',
    iosClientId: '897007121549-g2t12vflr1reo86m65sb9b3f3665kq5c.apps.googleusercontent.com',
    iosBundleId: 'com.foodbridge.app.testProject',
  );
}
